### PR TITLE
Brad/icon alignment fixes

### PR DESCRIPTION
**Pull request by bbraithwaite**
This PR contains two visual adjustments:

1. 'align close button' - tweaks the vertical alignment of the close button in the search bar.

2. 'adjust checkbox padding and alignment' - this corrects the clipping of the bottom of the checkbox's grey bg when unchecked. The checkbox row padding should now also exactly match the row alignment of the bang options.

__Before__

before

__After__

after

### CODE REVIEW

**Comment by mrshu** [comment]
@bbraithwaite thanks a ton!

Unfortunately, the clipping still seems to be broken on my Linux machine, see the screenshot below:
un

I went ahead and created an installable version of your current branch (and pushed it to this branch, I hope that is OK) and will try to conduct more tests on more platform. It easily might be that this is a local problem on my machine.

**Comment by mrshu** [comment]
I did some more testing and it really seems that this is a local issue on my Chromium in a Linux box. 

Here are some tests I did on Windows 10

win10

and Windows 7

win7

Interestingly enough, this PR also looks very good in Chrome on Linux too

linux_chrome

I would like @thm to take one last look on his Mac and then I think this is good to go.

Thanks a ton again @bbraithwaite!

**Comment by thm** [comment]
LGTM!

**Comment by mrshu** [comment]
Thanks everyone!

**Comment by bbraithwaite** [comment]
:+1: Good catch, I overlooked incrementing the version number!

**Pull request merged**
