### PR TITLE
Add Grunt and Handlebars

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
**Reviewer:** @jdorweiler 

## Description:

The existing extension has little infrastructure: no build system, no Handlebars templates, no Sass.
So, as a first step:
- Add Grunt and Handlebars to package.json
- Add Gruntfile with tasks to compile Handlebars templates and concatenate them with popup.js
- Add templates/ dir for Handlebars templates and static/js/ for the compiled result
- Take out hardcoded HTML inside popup.js and use two Handlebars templates instead, for tracking domains and request counts shown in the popup
- Import Handlebars and static JS in popup.html

The static JS is pushed as well for ease of testing

## Steps to test this PR:
Since we're now using templates for the trackers list, we want to test whether that function is intact and blocked domains are shown correctly.

1. Load any website
2. Open popup and look at the trackers list
3. Verify the list of trackers is shown correctly: domains and requests match the number of blocked trackers in the icon badge
4. Repeat from step 1. with other websites

## Automated tests:
- [x] Unit tests
- [x] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Comment by jdorweiler** [comment]
Can you update the REAME with instructions on how to setup and run grunt?

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Done! How does it look?

**Comment by jdorweiler** [comment]
Getting this error
```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'load-grunt-tasks'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by jdorweiler** [comment]
Running `npm install` again fixed it. 

I'm getting broken images though. 
screen shot 2017-04-18 at 9 19 20 am

**Comment by MariagraziaAlastra** [comment]
@jdorweiler That's not related to this change, I think it's about the paths specified in the JSON data, from last week's PR

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Should be fixed now

**Comment by jdorweiler** [comment]
👍

**Pull request merged**
