### PR TITLE
Add ToSDR to privacy grade

### PR DESCRIPTION
**Pull request by jdorweiler**
**Reviewer:**

## Description:

I gathered all of the ToSDR data using `scripts/tosdr.js` and processed into our own internal data structure that we will use to adjust the privacy grade.
https://github.com/duckduckgo/chrome-zeroclickinfo/compare/beta...jd/tosdr?expand=1#diff-b5b236475963defb1316e2989db286f6

The overall adjustment to the grade is pre-calculated and includes a `match` object that lists the good and bad reasons for the grade. 

I manually built a list of all of the good and bad privacy sounding topics to use for adjusting the grade. 
https://github.com/duckduckgo/chrome-zeroclickinfo/compare/beta...jd/tosdr?expand=1#diff-26cd4543b120a64e612a321d503a8996

When grading a site there is a new tosdr property that contains the overall score and reasons for the adjustment. 

screen shot 2017-08-31 at 4 50 39 pm

## Steps to test this PR:

- test http://mint.com before loading this PR. It should be a "C"
- load this PR and visit the site again. It's now a "D" since it has one bad ToSDR topic.
https://github.com/duckduckgo/chrome-zeroclickinfo/compare/beta...jd/tosdr?expand=1#diff-b5b236475963defb1316e2989db286f6R452

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Comment by J-tt** [comment]
This looks quite interesting, definitely a good addition to DDG. Is there any plans in place to update `tosdr.json` if the data gets updated, as site ratings could change due to TOS updates.

The use of static data for a dynamic resource always worries me, so it may be better to pull the data from the API (although that may cause issues with hitting the it too much).

**Comment by jdorweiler** [comment]
I'll have `tosdr.js` run somewhere in the release process if we decide to go with this. That way we have the latest data whenever we send a new version to Firefox.

**Comment by J-tt** [comment]
Yeah, sounds good. I'll patch this into my Firefox compatible fork as well 👍

**Comment by russellholt** [comment]
LGTM. Noting that we should pull the tosdr repo in the future.

**Comment by J-tt** [comment]
Shouldn't this get closed now?

**Pull request merged**
