### PR TITLE
fixing css of checkboxes under special

### PR DESCRIPTION
**Pull request by Sayanc93**
Fixed the css of checkboxes under special
Before:
screen shot 2016-01-31 at 2 59 34 pm

After the change:
screen shot 2016-01-31 at 3 31 02 pm

### CODE REVIEW

**Comment by mrshu** [comment]
@Sayanc93 Same as #15, thanks a ton again! I will leave this PR in @bbraithwaite's capable hands.

**Comment by bbraithwaite** [comment]
This looks great. I have a couple of additional tweaks to make for another change, so will merge this in along with those changes early next week. Same for: https://github.com/duckduckgo/chrome-zeroclickinfo/pull/15

**Comment by Sayanc93** [comment]
@mrshu - hey where can I talk to you to discuss about the approach on making custom bangs in the extension popup?

**Comment by bbraithwaite** [comment]
:+1:

**Pull request merged**
