### PR TITLE
build script

### PR DESCRIPTION
**Pull request by jdorweiler**
**Reviewer:**

## Description:

1. update the makefile to include a "release" target. This will create a release directory and copy over only the files needed to run the extension. I removed a lot of unused targets from the makefile to clean it up.

2. Deleted an unused file and removed some commented code

## Steps to test this PR:

1. run `make release`
2. load the extension from the release directory

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Comment by laurengarcia** [comment]
When running `make release` my local CLI is complaining `python2:  command not found` (I do have python 2.x tho). Sounds like an alias local to your machine? Is this expected?

**Comment by laurengarcia** [comment]
Ok, fixed two things. I can push these fixes up or you can, but here's what needed to change to get it to work without errors:

1- create a `release` directory. Will need some kind of way of keeping the empty dir since the Makefile assumes it exists in line 19.

2- remove `python2` alias that is probably unique to your setup from line 7 in favor of just `python`.

Another suggestion: maybe just `rm -rf` the js/ui directory since it is empty/redundant. Just so Mozilla cant complain about it.

Let me know and I'll send a commit with changes or you can. Otherwise, looks good.

**Comment by laurengarcia** [comment]
Another thought: do we want separate dirs for chrome && FF? 
Maybe `release-ff` and `release-chrome` or something like that.

**Comment by jdorweiler** [comment]
I updated the makefile and remove all the old stuff we didn't need in there. Building Firefox and Chrome should be the same. Depends more on which branch you're on, `beta` vs `beta-firefox`.

**Comment by laurengarcia** [comment]
Keep forgetting about `beta-firefox`. All looks good now, merge at will.

**Pull request merged**
