### PR TITLE
re-enable atb module and changes for Firefox

### PR DESCRIPTION
**Pull request by jdorweiler**
**Reviewer:**

## Description:

- re-enabled the atb module and updated the unit test
- fix the settings popup url for Firefox
- add `applications` to the manifest so we can load this as a webextension in Firefox

## Steps to test this PR:

- To load in Firefox: about:debugging -> load temporary addon
- Run unit tests
- This branch should also work in Chrome without any problems

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Comment by laurengarcia** [comment]
Seeing the atb param everywhere EXCEPT the home page -- should we make sure its added there too?

**Comment by laurengarcia** [comment]
atb-unittest-ffnightly
atb-ffnightly

**Comment by jdorweiler** [comment]
Something is up with that test in nightly. I'll check it out. For the atb params, do you see any console errors? It's working for me in 58.

**Comment by laurengarcia** [comment]
I don't remember any console errors unfortunately. I installed against a fresh profile on FF Nightly v58, if that's any help...

**Comment by jdorweiler** [comment]
Should be fixed now. Did you load it from scratch or reload an existing extension? If you reload an existing extension it fires an 'upgrade' instead of 'install' event. Either way that's a legit bug. I updated it to calculate a new atb for both events (assuming you don't already have atb).

**Comment by laurengarcia** [comment]
I had tested earlier from a fresh profile in Firefox. In Chrome, I usually delete and then re-install when testing, too (which seems functionally equivalent to fresh profile in FF).

**Comment by jdorweiler** [comment]
How about now? Are you able to repeat that with the latest changes?

**Comment by laurengarcia** [comment]
Checking...

**Comment by laurengarcia** [comment]
Confirming unit tests now passing in Firefox (in addition to Chrome as before), manual testing also confirms ATB value is being sent to SERP in both browsers.

Merging.

**Pull request merged**
