### PR TITLE
fix abp module

### PR DESCRIPTION
**Pull request by jdorweiler**
**Reviewer:**

## Description:

There's a bug in the abp module that doesn't handle escaped forward slashes in a regex entry. 

Entries like `/\.accountant\/[0-9]{2,9}\/` were being parsed out as `\.accountant\/[0-9]{2,9}\` which is an invalid regex.

I'll submit a PR to the module maintainer to see if we can get it fixed. But for now I'm going to stop building abp.js with grunt and include the module with my fix in the repo.

The bug fix is here: https://github.com/duckduckgo/chrome-zeroclickinfo/compare/beta...jd/abp-module?expand=1#diff-d12a9002374b7a83cbe22ffb0bf37dacR243

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Comment by laurengarcia** [comment]
A nice pattern I've seen for situations like this in open source is to fork the offending repo in github, apply your change, submit PR against your fork/branch, and then point the npm dependency at your own repo in `package.json` like so:
```
"dependencies" : {
  "name1" : "git://github.com/user/project.git#commit-ish",
}
```
That would prevent you from having to commit the built file here and alter the Gruntfile. It's a nicer placeholder IMO.

More info:
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by laurengarcia** [comment]
1) Can we remove js/abp.js from the repo now since the dependency issue is resolved with nice package.json pattern?

2) Am going to push up a postinstall hook to this branch that does the `npm install` in the abp node_modules dir automatically. Hope that's ok (it can be backed out if not).

**Comment by jdorweiler** [comment]
> Can we remove js/abp.js from the repo now since the dependency issue is resolved with nice package.json pattern?

Done! totally forgot about that.

> Am going to push up a postinstall hook to this branch that does the npm install in the abp node_modules dir automatically. Hope that's ok (it can be backed out if not).

👍

**Comment by laurengarcia** [comment]
Beauty! LGTM

**Pull request merged**
