### PR TITLE
UI fix for button

### PR DESCRIPTION
**Pull request by gabhi**
screen shot 2016-02-14 at 11 20 15 pm

### CODE REVIEW

**Comment by mrshu** [comment]
@bbraithwaite can you please take a look at this?

**Comment by mrshu** [comment]
@gabhi Thanks a ton, I cannot really reproduce the issue, would you mind telling us what OS/Chrome version od you use?

@bbraithwaite would you mind taking a look at this?

**Comment by gabhi** [comment]
@mrshu I am on Mac os EL Capitan 10.11.4 Beta (15E33e). Chrome version Version 48.0.2564.109 (64-bit)

**Comment by bbraithwaite** [comment]
I think the problem in the screen shot has already been addressed on this master branch? We are due a new release?

**Comment by mrshu** [comment]
That is right @bbraithwaite, I am no sure where does the screenshot come from.

@gabhi can you please confirm that the screenshot is from the master version of the extension? By that I mean the one that is available from here: https://github.com/duckduckgo/chrome-zeroclickinfo/blob/master/build/chrome-zeroclick-latest.crx?raw=true

**Comment by nirajkaushal** [comment]
I think he is working on  version 42.5.25(chrome-zeroclickinfo extension) downloaded from chrome store.
@gabhi  we are working on latest version 42.5.34 and in this version it is already patched.

**Comment by gabhi** [comment]
ohh i see. Thanks @nirajkaushal Closing this

**Pull request closed without merging**
