### PR TITLE
screenshot testing

### PR DESCRIPTION
**Pull request by jdorweiler**
**Reviewer:**

## Description:

Updated the `test/index.html` page to include links to unit tests, open top 10 popular sites, and screenshot testing. 

Running screenshot tests will open links in a new tab, first with tracking/https on, then with tracking/https off. After all sites are finished loading a side-by-side comparison table of images will be generated. 

screen shot 2017-05-25 at 12 50 08 pm

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

### CODE REVIEW

**Comment by jdorweiler** [comment]
Updated this to also do debugging for single sites and cleaned up the screenshot comparison test.

To test the site debugger try the following:
- remove the whitelist entry from `data/tracker_lists/general-whitelist.txt` and reload the extension. This will cause some wordpress sites to break. 
- go to http://chicago.suntimes.com and verify the page is broken
- go to the extension test page `test/index.html`
- in the site debugger box inter `chicago.suntimes.com`, and run
- wait for the test to finish and then look at the screenshots. It should be easy to see which blocked tracker broke the page
- click on the blocked tracker link above the screenshot. The test will rerun with this tracker whitelisted. 
- all the screenshots should look fine now

screen shot 2017-07-18 at 12 06 15 pm

**Comment by laurengarcia** [comment]
Sorry, I haven't forgotten about this. Just want to be sure that I put full attention on it because its important and there's been alot of distractions this week. Coming back asap tho. Thanks for doing this.

**Comment by laurengarcia** [comment]
Found an issue in the ATB unit tests. Have a fix on my box I can push up if you like. Basically it seems to boil down to the test for ""got new set_atb value from success page" and the test for "new tab url has atb param" are running in parallel, seems like the expectation the code has is that they will run in the order they appear in the code. Its an async problem that can be fixed by moving the test that fails into the callback for the one before it. Otherwise it fails for me locally.

screen shot 2017-07-24 at 1 52 36 pm

**Comment by laurengarcia** [comment]
One other small thing: might want to add an `http://` before the "debug sites" input on `test/index.html` page. First shot at it I loaded `http://chicago.suntimes.com` instead of just `chicago.suntimes.com` and it errored out with no feedback.

Other than that, this is a tremendous step forward. Stoked.

**Comment by laurengarcia** [comment]
Whoops, one more thing: there are some minor errors in the `test/index.html` output itself. Looks like bad mapping of files that are creating 404 errors. See screenshot.

screen shot 2017-07-24 at 2 36 33 pm

**Comment by jdorweiler** [comment]
@laurengarcia ready to go again.

**Comment by laurengarcia** [comment]
This looks done. I'm just going to go ahead and merge this so I can hook up to HTTPS Everywhere. Straggling issues can be fixed later.

**Pull request merged**
